/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ATS;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Reha
 */
public class Advisor extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement pst = null;
    
    /**
     * Creates new form Test
     */
    public Advisor() {
        initComponents();
    }

    public Advisor(String id) 
    {
        initComponents();
        conn = Driver.ConnectDB();

        //Seeting the visibility when a admin page opens so only dashboard can be seen
        Dashboard.setVisible(true);
        Backup.setVisible(false);
        Sale.setVisible(false);
        userAccPanel.setVisible(false);
        cardLabel.setVisible(false);
        tcardid.setVisible(false);
        userIdLabel.setText(id);
        userIdLabel.setVisible(false);
        
        String blanksql = "SELECT blankId from blanks WHERE user_userid = '" + userIdLabel.getText() + "' and Validity != 'void'";
        try
        {
            pst = conn.prepareStatement(blanksql);
            ResultSet rs = pst.executeQuery(blanksql);
            
            while (rs.next()) {
                tblank.addItem(rs.getString("blankId"));
            }
            
        }
        catch (Exception e)
        {
        }
        
        String refundsql = "SELECT RefundID from refunds";
        try
        {
            pst = conn.prepareStatement(refundsql);
            ResultSet rs = pst.executeQuery(refundsql);
            
            while (rs.next()) {
                tblank.addItem(rs.getString("RefundID"));
            }
            
        }
        catch (Exception e)
        {
        }
        
        String exchangeratesql = "SELECT CurrencyName from exchangerate";
        try
        {
            pst = conn.prepareStatement(exchangeratesql);
            ResultSet rs = pst.executeQuery(exchangeratesql);
            
            while (rs.next()) {
                tCurrency.addItem(rs.getString("CurrencyName"));
            }
            
        }
        catch (Exception e)
        {
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateDay = new javax.swing.JComboBox<String>();
        dateMonth = new javax.swing.JComboBox<String>();
        dateYear = new javax.swing.JComboBox<String>();
        buttonGroup1 = new javax.swing.ButtonGroup();
        Backup = new javax.swing.JPanel();
        AdminBackPanel = new javax.swing.JPanel();
        AdminMenuPanel = new javax.swing.JPanel();
        homeBtn = new javax.swing.JButton();
        addSalesBtn = new javax.swing.JButton();
        generateReportBtn = new javax.swing.JButton();
        rLogOut = new javax.swing.JButton();
        Sales = new javax.swing.JButton();
        cancelSaleBtn = new javax.swing.JButton();
        checkStocksBtn = new javax.swing.JButton();
        AdminDynamicPanel = new javax.swing.JPanel();
        Dashboard = new javax.swing.JPanel();
        userIdLabel = new javax.swing.JLabel();
        Sale = new javax.swing.JPanel();
        modifySalePanel = new javax.swing.JPanel();
        name2 = new javax.swing.JLabel();
        username3 = new javax.swing.JLabel();
        role2 = new javax.swing.JLabel();
        tname = new javax.swing.JTextField();
        name3 = new javax.swing.JLabel();
        username4 = new javax.swing.JLabel();
        username5 = new javax.swing.JLabel();
        torigin = new javax.swing.JTextField();
        tothertax = new javax.swing.JTextField();
        password5 = new javax.swing.JLabel();
        otherlabel = new javax.swing.JLabel();
        password7 = new javax.swing.JLabel();
        payment = new javax.swing.JComboBox<String>();
        cardLabel = new javax.swing.JLabel();
        password8 = new javax.swing.JLabel();
        rRegister3 = new javax.swing.JButton();
        rUpdate = new javax.swing.JButton();
        rCancel = new javax.swing.JButton();
        dateDay1 = new javax.swing.JComboBox<String>();
        dateMonth1 = new javax.swing.JComboBox<String>();
        dateYear1 = new javax.swing.JComboBox<String>();
        name4 = new javax.swing.JLabel();
        tblank = new javax.swing.JComboBox();
        tCurrency = new javax.swing.JComboBox();
        tcost = new javax.swing.JTextField();
        tcardid = new javax.swing.JTextField();
        tdestination1 = new javax.swing.JTextField();
        tlocaltax = new javax.swing.JTextField();
        userAccPanel = new javax.swing.JPanel();
        registerPanel = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        ttype = new javax.swing.JComboBox<String>();
        role = new javax.swing.JLabel();
        tname1 = new javax.swing.JTextField();
        rRegister = new javax.swing.JButton();
        rUpdate1 = new javax.swing.JButton();
        id = new javax.swing.JLabel();
        tid = new javax.swing.JTextField();
        rDelete1 = new javax.swing.JButton();
        viewBtn = new javax.swing.JButton();
        Refund = new javax.swing.JPanel();
        modifySalePanel1 = new javax.swing.JPanel();
        name6 = new javax.swing.JLabel();
        rRegister4 = new javax.swing.JButton();
        rCancel1 = new javax.swing.JButton();
        tblank1 = new javax.swing.JComboBox();
        AdminTopPanel = new javax.swing.JPanel();
        AirViaLtdLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        dateDay.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        dateMonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        dateYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2015", "2016", "2017", "2018", "2019", "2020" }));

        Backup.setBackground(new java.awt.Color(241, 223, 200));

        javax.swing.GroupLayout BackupLayout = new javax.swing.GroupLayout(Backup);
        Backup.setLayout(BackupLayout);
        BackupLayout.setHorizontalGroup(
            BackupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 851, Short.MAX_VALUE)
        );
        BackupLayout.setVerticalGroup(
            BackupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1961, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AdminBackPanel.setBackground(new java.awt.Color(255, 255, 255));

        homeBtn.setText("Home");
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        addSalesBtn.setText("Customer Registration");
        addSalesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSalesBtnActionPerformed(evt);
            }
        });

        generateReportBtn.setText("Reports");
        generateReportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateReportBtnActionPerformed(evt);
            }
        });

        rLogOut.setText("Log Out");
        rLogOut.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rLogOutActionPerformed(evt);
            }
        });

        Sales.setText("Sales");
        Sales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalesActionPerformed(evt);
            }
        });

        cancelSaleBtn.setText("Refunds");
        cancelSaleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelSaleBtnActionPerformed(evt);
            }
        });

        checkStocksBtn.setText("Check Stocks");
        checkStocksBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkStocksBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AdminMenuPanelLayout = new javax.swing.GroupLayout(AdminMenuPanel);
        AdminMenuPanel.setLayout(AdminMenuPanelLayout);
        AdminMenuPanelLayout.setHorizontalGroup(
            AdminMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AdminMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(generateReportBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Sales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addSalesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(homeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancelSaleBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(checkStocksBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        AdminMenuPanelLayout.setVerticalGroup(
            AdminMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addSalesBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Sales)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelSaleBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkStocksBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(generateReportBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rLogOut)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Dashboard.setBackground(new java.awt.Color(241, 223, 200));
        Dashboard.setPreferredSize(new java.awt.Dimension(763, 531));

        userIdLabel.setText("jLabel1");

        javax.swing.GroupLayout DashboardLayout = new javax.swing.GroupLayout(Dashboard);
        Dashboard.setLayout(DashboardLayout);
        DashboardLayout.setHorizontalGroup(
            DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardLayout.createSequentialGroup()
                .addGap(514, 514, 514)
                .addComponent(userIdLabel)
                .addContainerGap(215, Short.MAX_VALUE))
        );
        DashboardLayout.setVerticalGroup(
            DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardLayout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(userIdLabel)
                .addContainerGap(293, Short.MAX_VALUE))
        );

        Sale.setBackground(new java.awt.Color(241, 223, 200));
        Sale.setPreferredSize(new java.awt.Dimension(767, 684));

        modifySalePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Sales"));

        name2.setText("Customer Name:");

        username3.setText("Fare");

        role2.setText("Form of payment:");

        name3.setText("Blank:");

        username4.setText("Origin:");

        username5.setText("Destination:");

        password5.setText("Taxes");

        otherlabel.setText("Other:");

        password7.setText("Local:");

        payment.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cash", "Credit Card", "Late Payment" }));
        payment.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                paymentItemStateChanged(evt);
            }
        });

        cardLabel.setText("Credit Card:");

        password8.setText("Local currency:");

        rRegister3.setText("Add Sale");
        rRegister3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rRegister3ActionPerformed(evt);
            }
        });

        rUpdate.setText("Modify Sale");
        rUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rUpdateActionPerformed(evt);
            }
        });

        rCancel.setText("Cancel Sale");
        rCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rCancelActionPerformed(evt);
            }
        });

        dateDay1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        dateMonth1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        dateYear1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2015", "2016", "2017", "2018", "2019", "2020" }));

        name4.setText("Date:");

        tblank.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tblankItemStateChanged(evt);
            }
        });

        tcost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcostActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout modifySalePanelLayout = new javax.swing.GroupLayout(modifySalePanel);
        modifySalePanel.setLayout(modifySalePanelLayout);
        modifySalePanelLayout.setHorizontalGroup(
            modifySalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modifySalePanelLayout.createSequentialGroup()
                .addGroup(modifySalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(modifySalePanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(modifySalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(password8)
                            .addComponent(username4)
                            .addComponent(name4)
                            .addComponent(name2)
                            .addComponent(name3)
                            .addComponent(username3)
                            .addComponent(username5))
                        .addGap(18, 18, 18))
                    .addGroup(modifySalePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(modifySalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(password5)
                            .addComponent(password7)
                            .addComponent(otherlabel)
                            .addComponent(role2)
                            .addComponent(cardLabel))
                        .addGap(22, 22, 22)))
                .addGroup(modifySalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modifySalePanelLayout.createSequentialGroup()
                        .addComponent(tname, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(189, 189, 189))
                    .addGroup(modifySalePanelLayout.createSequentialGroup()
                        .addGroup(modifySalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tcardid, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(modifySalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tothertax, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(torigin, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, modifySalePanelLayout.createSequentialGroup()
                                    .addComponent(dateDay1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(dateMonth1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(dateYear1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(tblank, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tdestination1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(modifySalePanelLayout.createSequentialGroup()
                                    .addComponent(tcost, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                    .addGap(18, 18, 18)
                                    .addComponent(tCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(tlocaltax, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(payment, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(12, 12, 12))))
            .addGroup(modifySalePanelLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(rRegister3)
                .addGap(50, 50, 50)
                .addComponent(rCancel)
                .addGap(42, 42, 42)
                .addComponent(rUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(189, 189, 189))
        );
        modifySalePanelLayout.setVerticalGroup(
            modifySalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modifySalePanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(modifySalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateDay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateMonth1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateYear1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(modifySalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(modifySalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name3)
                    .addComponent(tblank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(username3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(modifySalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username4)
                    .addComponent(torigin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(modifySalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tdestination1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(username5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(modifySalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password8)
                    .addComponent(tcost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(modifySalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password7)
                    .addComponent(tlocaltax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(modifySalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(otherlabel)
                    .addComponent(tothertax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(modifySalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(role2)
                    .addComponent(payment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(modifySalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cardLabel)
                    .addComponent(tcardid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(modifySalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rRegister3)
                    .addComponent(rCancel)
                    .addComponent(rUpdate))
                .addGap(106, 106, 106))
        );

        javax.swing.GroupLayout SaleLayout = new javax.swing.GroupLayout(Sale);
        Sale.setLayout(SaleLayout);
        SaleLayout.setHorizontalGroup(
            SaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SaleLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(modifySalePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(171, Short.MAX_VALUE))
        );
        SaleLayout.setVerticalGroup(
            SaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SaleLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(modifySalePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        userAccPanel.setBackground(new java.awt.Color(241, 223, 200));
        userAccPanel.setPreferredSize(new java.awt.Dimension(863, 706));

        registerPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "User accounts:", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        name.setText("Name:");

        ttype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Regular", "Valued", "Casual" }));

        role.setText("Customer Type");

        rRegister.setText("Add Customer");
        rRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rRegisterActionPerformed(evt);
            }
        });

        rUpdate1.setText("Update Customer");
        rUpdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rUpdate1ActionPerformed(evt);
            }
        });

        id.setText("Id:");

        rDelete1.setText("Delete Customer");
        rDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rDelete1ActionPerformed(evt);
            }
        });

        viewBtn.setText("View Customers");
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registerPanelLayout = new javax.swing.GroupLayout(registerPanel);
        registerPanel.setLayout(registerPanelLayout);
        registerPanelLayout.setHorizontalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerPanelLayout.createSequentialGroup()
                        .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(name)
                            .addComponent(id)
                            .addComponent(role))
                        .addGap(18, 18, 18)
                        .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tname1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tid, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ttype, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(113, 113, 113))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerPanelLayout.createSequentialGroup()
                        .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(rDelete1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rRegister))
                        .addGap(44, 44, 44)
                        .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rUpdate1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68))))
        );
        registerPanelLayout.setVerticalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name)
                    .addComponent(tname1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ttype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(role))
                .addGap(18, 18, 18)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rRegister)
                    .addComponent(rUpdate1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rDelete1)
                    .addComponent(viewBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout userAccPanelLayout = new javax.swing.GroupLayout(userAccPanel);
        userAccPanel.setLayout(userAccPanelLayout);
        userAccPanelLayout.setHorizontalGroup(
            userAccPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userAccPanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(registerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(387, Short.MAX_VALUE))
        );
        userAccPanelLayout.setVerticalGroup(
            userAccPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userAccPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(registerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1195, Short.MAX_VALUE))
        );

        Refund.setBackground(new java.awt.Color(241, 223, 200));
        Refund.setPreferredSize(new java.awt.Dimension(767, 684));

        modifySalePanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Refunds"));

        name6.setText("Blank:");

        rRegister4.setText("Returned");
        rRegister4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rRegister4ActionPerformed(evt);
            }
        });

        rCancel1.setText("Refunded");
        rCancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rCancel1ActionPerformed(evt);
            }
        });

        tblank1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tblank1ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout modifySalePanel1Layout = new javax.swing.GroupLayout(modifySalePanel1);
        modifySalePanel1.setLayout(modifySalePanel1Layout);
        modifySalePanel1Layout.setHorizontalGroup(
            modifySalePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modifySalePanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(name6)
                .addGap(18, 18, 18)
                .addGroup(modifySalePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(modifySalePanel1Layout.createSequentialGroup()
                        .addComponent(rRegister4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rCancel1))
                    .addComponent(tblank1, 0, 251, Short.MAX_VALUE))
                .addGap(165, 165, 165))
        );
        modifySalePanel1Layout.setVerticalGroup(
            modifySalePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modifySalePanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(modifySalePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name6)
                    .addComponent(tblank1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(modifySalePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rRegister4)
                    .addComponent(rCancel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout RefundLayout = new javax.swing.GroupLayout(Refund);
        Refund.setLayout(RefundLayout);
        RefundLayout.setHorizontalGroup(
            RefundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RefundLayout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addComponent(modifySalePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );
        RefundLayout.setVerticalGroup(
            RefundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RefundLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(modifySalePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout AdminDynamicPanelLayout = new javax.swing.GroupLayout(AdminDynamicPanel);
        AdminDynamicPanel.setLayout(AdminDynamicPanelLayout);
        AdminDynamicPanelLayout.setHorizontalGroup(
            AdminDynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminDynamicPanelLayout.createSequentialGroup()
                .addComponent(userAccPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 88, Short.MAX_VALUE))
            .addGroup(AdminDynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(AdminDynamicPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 863, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(AdminDynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminDynamicPanelLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Sale, javax.swing.GroupLayout.DEFAULT_SIZE, 927, Short.MAX_VALUE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(AdminDynamicPanelLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Refund, javax.swing.GroupLayout.DEFAULT_SIZE, 927, Short.MAX_VALUE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        AdminDynamicPanelLayout.setVerticalGroup(
            AdminDynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminDynamicPanelLayout.createSequentialGroup()
                .addComponent(userAccPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1417, Short.MAX_VALUE)
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(AdminDynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminDynamicPanelLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(AdminDynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(AdminDynamicPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Sale, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(Refund, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        AdminTopPanel.setBackground(new java.awt.Color(0, 0, 51));

        AirViaLtdLabel.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        AirViaLtdLabel.setForeground(new java.awt.Color(255, 153, 51));
        AirViaLtdLabel.setText("AirViaLtd");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ATS/images/plane.png"))); // NOI18N

        javax.swing.GroupLayout AdminTopPanelLayout = new javax.swing.GroupLayout(AdminTopPanel);
        AdminTopPanel.setLayout(AdminTopPanelLayout);
        AdminTopPanelLayout.setHorizontalGroup(
            AdminTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminTopPanelLayout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AirViaLtdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AdminTopPanelLayout.setVerticalGroup(
            AdminTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminTopPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(AdminTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdminTopPanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(AirViaLtdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout AdminBackPanelLayout = new javax.swing.GroupLayout(AdminBackPanel);
        AdminBackPanel.setLayout(AdminBackPanelLayout);
        AdminBackPanelLayout.setHorizontalGroup(
            AdminBackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminBackPanelLayout.createSequentialGroup()
                .addComponent(AdminMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(AdminDynamicPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(AdminTopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        AdminBackPanelLayout.setVerticalGroup(
            AdminBackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminBackPanelLayout.createSequentialGroup()
                .addComponent(AdminTopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AdminBackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AdminMenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AdminDynamicPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AdminBackPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AdminBackPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1038, 852));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblankItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tblankItemStateChanged
        // TODO add your handling code here
    }//GEN-LAST:event_tblankItemStateChanged

    private void rUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rUpdateActionPerformed
        String dateRecieved = dateYear.getSelectedItem().toString() + "/"
        + dateMonth.getSelectedItem().toString() + "/" + dateDay.getSelectedItem().toString();
        String customerID = tname.getText();
        String sql2 = "UPDATE blanks set Departure = '" + torigin.getText() + "', Arrival = '" + tothertax.getText() + "', Validity = 'valid' WHERE blankId = '" + tblank.getSelectedItem() + "'";
        String sql3 = "SELECT CurrentRate FROM exchangerate WHERE CurrencyName = '" + tCurrency.getSelectedItem().toString() + "'";
        String sql4 = "UPDATE creditcard set CardID = '" + tcardid.getText() + "')";
        //If all fields are field in the show register sucessful message
        try {
            if (!(tname.getText().trim().isEmpty()) && !(torigin.getText().trim().isEmpty())
                && !(tothertax.getText().trim().isEmpty()) && !(tcost.getText().trim().isEmpty())) {

                if (payment.getSelectedItem() == "Credit Card")
                {
                    if (!(tcardid.getText().trim().isEmpty()))
                    {
                        pst = conn.prepareStatement(sql4);
                        pst.executeUpdate(sql4);
                    } else {
                        JOptionPane.showMessageDialog(null, "Fill in all fields.");
                        return;
                    }
                }

                pst = conn.prepareStatement(sql2);
                pst.executeUpdate(sql2);
                pst = conn.prepareStatement(sql3);
                ResultSet rs = pst.executeQuery();
                Double cost = Double.parseDouble(tcost.getText());
                if (rs.next()) {
                    cost *= rs.getDouble(1);

                }

                String sql5 = "UPDATE payments set PaymentID = '" + tblank.getSelectedItem().toString() + "', Amount = '"+ cost + "', PaymentType =  '" + payment.getSelectedItem().toString() + "', customer_customerID =  (SELECT customerID from Customer WHERE customerID = '" + customerID + "'), exchangerate_CurrencyName = (SELECT CurrencyName from exchangerate WHERE CurrencyName = '" + tCurrency.getSelectedItem().toString() + "')";
                pst = conn.prepareStatement(sql5);
                pst.executeUpdate(sql5);

                String sql6 = "UPDATE sales Date = '" + dateRecieved + "', blanks_blankId = '" + tblank.getSelectedItem().toString() + "', customer_customerID = (SELECT customerID from Customer WHERE customerID = '" + customerID + "'), user_userID = (SELECT userId from users WHERE userId = '" + userIdLabel.getText() + "')";
                pst = conn.prepareStatement(sql6);
                pst.executeUpdate(sql6);

                JOptionPane.showMessageDialog(null, "Registration Succussful.");

            } else {
                JOptionPane.showMessageDialog(null, "Fill in all fields.");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_rUpdateActionPerformed

    private void rRegister3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rRegister3ActionPerformed
        String dateRecieved = dateYear.getSelectedItem().toString() + "/"
        + dateMonth.getSelectedItem().toString() + "/" + dateDay.getSelectedItem().toString();
        String customerID = tname.getText();
        String sql2 = "UPDATE blanks set Departure = '" + torigin.getText() + "', Arrival = '" + tothertax.getText() + "', Validity = 'valid' WHERE blankId = '" + tblank.getSelectedItem() + "'";
        String sql3 = "SELECT CurrentRate FROM exchangerate WHERE CurrencyName = '" + tCurrency.getSelectedItem().toString() + "'";
        String sql4 = "INSERT INTO creditcard (CardID) values('" + tcardid.getText() + "')";
        //If all fields are field in the show register sucessful message
        try {
            if (!(tname.getText().trim().isEmpty()) && !(torigin.getText().trim().isEmpty())
                && !(tothertax.getText().trim().isEmpty()) && !(tcost.getText().trim().isEmpty())) {

                if (payment.getSelectedItem() == "Credit Card")
                {
                    if (!(tcardid.getText().trim().isEmpty()))
                    {
                        pst = conn.prepareStatement(sql4);
                        pst.executeUpdate(sql4);
                    } else {
                        JOptionPane.showMessageDialog(null, "Fill in all fields.");
                        return;
                    }
                }

                pst = conn.prepareStatement(sql2);
                pst.executeUpdate(sql2);
                pst = conn.prepareStatement(sql3);
                ResultSet rs = pst.executeQuery();
                Double cost = Double.parseDouble(tcost.getText());
                if (rs.next()) {
                    cost *= rs.getDouble(1);

                }

                String sql5 = "INSERT INTO payments (PaymentID, Amount, PaymentType, customer_customerID, exchangerate_CurrencyName) values ('" + tblank.getSelectedItem().toString() + "', '"+ cost + "', '" + payment.getSelectedItem().toString() + "', (SELECT customerID from Customer WHERE customerID = '" + customerID + "'), (SELECT CurrencyName from exchangerate WHERE CurrencyName = '" + tCurrency.getSelectedItem().toString() + "'))";
                pst = conn.prepareStatement(sql5);
                pst.executeUpdate(sql5);

                String sql6 = "INSERT INTO sales (Date, blanks_blankId, customer_customerID, user_userID) values ('" + dateRecieved + "', '" + tblank.getSelectedItem().toString() + "', (SELECT customerID from Customer WHERE customerID = '" + customerID + "'), (SELECT userId from users WHERE userId = '" + userIdLabel.getText() + "'))";
                pst = conn.prepareStatement(sql6);
                pst.executeUpdate(sql6);

                JOptionPane.showMessageDialog(null, "Registration Succussful.");

            } else {
                JOptionPane.showMessageDialog(null, "Fill in all fields.");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_rRegister3ActionPerformed

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        // TODO add your handling code here:
        //        new viewEmployees().setVisible(true);
    }//GEN-LAST:event_viewBtnActionPerformed

    private void rDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rDelete1ActionPerformed
        //
        String sql = "DELETE FROM customer WHERE customerID = '" + tid.getText() + "'";
        try {
            if (!(tid.getText().trim().isEmpty()) && !(tname1.getText().trim().isEmpty())) {

                pst = conn.prepareStatement(sql);
                pst.executeUpdate(sql);

                JOptionPane.showMessageDialog(null, "Registration Succussful.");

            } else {
                JOptionPane.showMessageDialog(null, "Fill in all fields.");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_rDelete1ActionPerformed

    private void rUpdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rUpdate1ActionPerformed

        String Sql = "UPDATE customer SET customerID = '" + tid.getText() + "', Name = '" + ttype.getSelectedItem() + "', Valued = '" + tname1.getText() + "'";

        //If all fields are field in the show register sucessful message
        try {
            if (!(tid.getText().trim().isEmpty()) && !(tname1.getText().trim().isEmpty())) {

                pst = conn.prepareStatement(Sql);
                pst.executeUpdate(Sql);

                JOptionPane.showMessageDialog(null, "Registration Succussful.");

            } else {
                JOptionPane.showMessageDialog(null, "Fill in all fields.");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_rUpdate1ActionPerformed

    private void rRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rRegisterActionPerformed

        String Sql = "insert into customer (customerID, Name, Valued)"
        + "values('" + tid.getText() + "', '" + ttype.getSelectedItem() + "', '" + tname1.getText() + "')";

        //If all fields are field in the show register sucessful message
        try {
            if (!(tid.getText().trim().isEmpty()) && !(tname1.getText().trim().isEmpty())) {

                pst = conn.prepareStatement(Sql);
                pst.executeUpdate(Sql);

                JOptionPane.showMessageDialog(null, "Registration Succussful.");

            } else {
                JOptionPane.showMessageDialog(null, "Fill in all fields.");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_rRegisterActionPerformed

    private void checkStocksBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkStocksBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkStocksBtnActionPerformed

    private void cancelSaleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelSaleBtnActionPerformed
        // TODO add your handling code here:
        Dashboard.setVisible(false);
        Backup.setVisible(false);
        Sale.setVisible(false);
        userAccPanel.setVisible(false);
    }//GEN-LAST:event_cancelSaleBtnActionPerformed

    private void SalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalesActionPerformed
        // TODO add your handling code here:
        Dashboard.setVisible(false);
        Backup.setVisible(false);
        Sale.setVisible(true);
        userAccPanel.setVisible(false);
    }//GEN-LAST:event_SalesActionPerformed

    private void rLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rLogOutActionPerformed
        // TODO add your handling code here:
        //Log out and go back to login page
        new Login().setVisible(true); //Make Login form visible
        this.dispose(); //Dispose of this form (Admin)
    }//GEN-LAST:event_rLogOutActionPerformed

    private void generateReportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateReportBtnActionPerformed
        // TODO add your handling code here:
        //Only register user page visible
        Dashboard.setVisible(false);
        Backup.setVisible(false);
        Sale.setVisible(false);
        userAccPanel.setVisible(false);
        new ViewSalesReports(userIdLabel.getText()).setVisible(true);
    }//GEN-LAST:event_generateReportBtnActionPerformed

    private void addSalesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSalesBtnActionPerformed
        // TODO add your handling code here:
        //Only backup page visible
        Backup.setVisible(false);
        Dashboard.setVisible(false);
        Sale.setVisible(false);
        userAccPanel.setVisible(true);
    }//GEN-LAST:event_addSalesBtnActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        // TODO add your handling code here:
        //Only dashboard visible
        Dashboard.setVisible(true);
        Backup.setVisible(false);
        Sale.setVisible(false);
        userAccPanel.setVisible(false);
    }//GEN-LAST:event_homeBtnActionPerformed

    private void rCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rCancelActionPerformed
        String sql = "UPDATE blanks set Validity = 'void' WHERE blankId = '" + tblank.getSelectedItem() + "' AND Validity = 'valid'";
        String sql2 = "INSERT INTO refunds (RefundID, Returned, Refunded) values ('" + tblank.getSelectedItem() + "', 0, 0)";
        try {
            pst = conn.prepareStatement(sql);
            pst.executeUpdate(sql);
            pst = conn.prepareStatement(sql2);
            pst.executeUpdate(sql2);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_rCancelActionPerformed

    private void paymentItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_paymentItemStateChanged
        // TODO add your handling code here:
        if (payment.getSelectedItem() == "Credit Card") {
            cardLabel.setVisible(true);
            tcardid.setVisible(true);
        } else {
            cardLabel.setVisible(false);
            tcardid.setVisible(false);
        }
    }//GEN-LAST:event_paymentItemStateChanged

    private void tcostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tcostActionPerformed

    private void tblank1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tblank1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_tblank1ItemStateChanged

    private void rCancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rCancel1ActionPerformed
        // TODO add your handling code here:
        String sql = "UPDATE refunds set Refunded = 1";
        try {
            pst = conn.prepareStatement(sql);
            pst.executeUpdate(sql);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }    
    }//GEN-LAST:event_rCancel1ActionPerformed

    private void rRegister4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rRegister4ActionPerformed
        // TODO add your handling code here:
        String sql = "UPDATE refunds set Returned = 1";
        try {
            pst = conn.prepareStatement(sql);
            pst.executeUpdate(sql);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }        
    }//GEN-LAST:event_rRegister4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Advisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Advisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Advisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Advisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Advisor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminBackPanel;
    private javax.swing.JPanel AdminDynamicPanel;
    private javax.swing.JPanel AdminMenuPanel;
    private javax.swing.JPanel AdminTopPanel;
    private javax.swing.JLabel AirViaLtdLabel;
    private javax.swing.JPanel Backup;
    private javax.swing.JPanel Dashboard;
    private javax.swing.JPanel Refund;
    private javax.swing.JPanel Sale;
    private javax.swing.JButton Sales;
    private javax.swing.JButton addSalesBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelSaleBtn;
    private javax.swing.JLabel cardLabel;
    private javax.swing.JButton checkStocksBtn;
    private javax.swing.JComboBox<String> dateDay;
    private javax.swing.JComboBox<String> dateDay1;
    private javax.swing.JComboBox<String> dateMonth;
    private javax.swing.JComboBox<String> dateMonth1;
    private javax.swing.JComboBox<String> dateYear;
    private javax.swing.JComboBox<String> dateYear1;
    private javax.swing.JButton generateReportBtn;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel modifySalePanel;
    private javax.swing.JPanel modifySalePanel1;
    private javax.swing.JLabel name;
    private javax.swing.JLabel name2;
    private javax.swing.JLabel name3;
    private javax.swing.JLabel name4;
    private javax.swing.JLabel name6;
    private javax.swing.JLabel otherlabel;
    private javax.swing.JLabel password5;
    private javax.swing.JLabel password7;
    private javax.swing.JLabel password8;
    private javax.swing.JComboBox<String> payment;
    private javax.swing.JButton rCancel;
    private javax.swing.JButton rCancel1;
    private javax.swing.JButton rDelete1;
    private javax.swing.JButton rLogOut;
    private javax.swing.JButton rRegister;
    private javax.swing.JButton rRegister3;
    private javax.swing.JButton rRegister4;
    private javax.swing.JButton rUpdate;
    private javax.swing.JButton rUpdate1;
    private javax.swing.JPanel registerPanel;
    private javax.swing.JLabel role;
    private javax.swing.JLabel role2;
    private javax.swing.JComboBox tCurrency;
    private javax.swing.JComboBox tblank;
    private javax.swing.JComboBox tblank1;
    private javax.swing.JTextField tcardid;
    private javax.swing.JTextField tcost;
    private javax.swing.JTextField tdestination1;
    private javax.swing.JTextField tid;
    private javax.swing.JTextField tlocaltax;
    private javax.swing.JTextField tname;
    private javax.swing.JTextField tname1;
    private javax.swing.JTextField torigin;
    private javax.swing.JTextField tothertax;
    private javax.swing.JComboBox<String> ttype;
    private javax.swing.JPanel userAccPanel;
    private javax.swing.JLabel userIdLabel;
    private javax.swing.JLabel username3;
    private javax.swing.JLabel username4;
    private javax.swing.JLabel username5;
    private javax.swing.JButton viewBtn;
    // End of variables declaration//GEN-END:variables
}
