/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ATS;

/**
 *
 * @author Reha
 */

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

public class Manager extends javax.swing.JFrame {
 Connection conn = null;
    PreparedStatement pst = null;
    PreparedStatement p = null;
    ResultSet rs = null;
    /**
     * Creates new form Dashboard
     */
    public Manager() {
        initComponents();        
        conn = Driver.ConnectDB();

        
        Dashboard.setVisible(true);
        AssignBlanks.setVisible(false);
        Commission.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ManagerDynamicPanel = new javax.swing.JPanel();
        Dashboard = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Currency = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        CurrencyName = new javax.swing.JTextField();
        CurrencyRate = new javax.swing.JTextField();
        getRateBtn = new javax.swing.JButton();
        setRateBtn = new javax.swing.JButton();
        Advisor = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        InputID = new javax.swing.JTextField();
        FindUser = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        AdvisorAddress = new javax.swing.JTextArea();
        AdvisorName = new javax.swing.JTextField();
        AssignBlanks = new javax.swing.JPanel();
        AssignBlanksPanel = new javax.swing.JPanel();
        blankType1 = new javax.swing.JLabel();
        blankTypeCombo1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lowerBlankNo1 = new javax.swing.JTextField();
        higherBlankNo1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        advisorId = new javax.swing.JTextField();
        AssignBtn = new javax.swing.JButton();
        Commission = new javax.swing.JPanel();
        AddAmount = new javax.swing.JTextField();
        AddCommBtn = new javax.swing.JButton();
        ChangeCommBtn = new javax.swing.JButton();
        CurrentAmount = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        ManagerTopPanel = new javax.swing.JPanel();
        AirViaLtdLabel16 = new javax.swing.JLabel();
        PlaneImg16 = new javax.swing.JLabel();
        ManagerMenuPanel = new javax.swing.JPanel();
        Home = new javax.swing.JButton();
        ReportsButton = new javax.swing.JButton();
        BlanksButton = new javax.swing.JButton();
        CommissionButton = new javax.swing.JButton();
        LogOut = new javax.swing.JButton();
        AdvisorBtn = new javax.swing.JButton();
        CurrencyBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(782, 475));

        ManagerDynamicPanel.setBackground(new java.awt.Color(241, 223, 200));

        Dashboard.setBackground(new java.awt.Color(241, 223, 200));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Welcome to the Manager Page.");

        javax.swing.GroupLayout DashboardLayout = new javax.swing.GroupLayout(Dashboard);
        Dashboard.setLayout(DashboardLayout);
        DashboardLayout.setHorizontalGroup(
            DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DashboardLayout.createSequentialGroup()
                .addContainerGap(229, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(133, 133, 133))
        );
        DashboardLayout.setVerticalGroup(
            DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardLayout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addComponent(jLabel1)
                .addContainerGap(240, Short.MAX_VALUE))
        );

        Currency.setBackground(new java.awt.Color(241, 223, 200));

        jLabel15.setText("Currency Name:");

        jLabel16.setText("Currency Rate:");

        CurrencyName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CurrencyNameActionPerformed(evt);
            }
        });

        getRateBtn.setText("Get Rate");
        getRateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getRateBtnActionPerformed(evt);
            }
        });

        setRateBtn.setText("Set Rate");
        setRateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setRateBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CurrencyLayout = new javax.swing.GroupLayout(Currency);
        Currency.setLayout(CurrencyLayout);
        CurrencyLayout.setHorizontalGroup(
            CurrencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CurrencyLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(CurrencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addGap(27, 27, 27)
                .addGroup(CurrencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CurrencyName, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(CurrencyRate))
                .addGap(83, 83, 83)
                .addGroup(CurrencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(getRateBtn)
                    .addComponent(setRateBtn))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        CurrencyLayout.setVerticalGroup(
            CurrencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CurrencyLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(CurrencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(CurrencyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getRateBtn))
                .addGap(90, 90, 90)
                .addGroup(CurrencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(CurrencyRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(setRateBtn))
                .addContainerGap(790, Short.MAX_VALUE))
        );

        Advisor.setBackground(new java.awt.Color(241, 223, 200));

        jLabel10.setText("AdvisorID");

        jLabel13.setText("Advisor Name:");

        jLabel14.setText("Advisor Address:");

        FindUser.setText("Find User");
        FindUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindUserActionPerformed(evt);
            }
        });

        AdvisorAddress.setColumns(20);
        AdvisorAddress.setRows(5);
        jScrollPane2.setViewportView(AdvisorAddress);

        javax.swing.GroupLayout AdvisorLayout = new javax.swing.GroupLayout(Advisor);
        Advisor.setLayout(AdvisorLayout);
        AdvisorLayout.setHorizontalGroup(
            AdvisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdvisorLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(AdvisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(AdvisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(AdvisorName)
                    .addComponent(InputID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(FindUser)
                .addGap(108, 108, 108))
        );
        AdvisorLayout.setVerticalGroup(
            AdvisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdvisorLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(AdvisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(InputID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FindUser))
                .addGap(23, 23, 23)
                .addGroup(AdvisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(AdvisorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AdvisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(235, Short.MAX_VALUE))
        );

        AssignBlanks.setBackground(new java.awt.Color(241, 223, 200));

        AssignBlanksPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Assign Blanks", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        blankType1.setText("Blank Type:");

        blankTypeCombo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "444", "440", "420", "201", "101", "451", "452" }));

        jLabel6.setText("Type in the last 8 digits of the blank number.");

        jLabel7.setText("Lowest Blank No:");

        jLabel8.setText("Highest Blank No:");

        lowerBlankNo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lowerBlankNo1ActionPerformed(evt);
            }
        });

        jLabel9.setText("Advisor ID:");

        advisorId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advisorIdActionPerformed(evt);
            }
        });

        AssignBtn.setText("Assign");
        AssignBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssignBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AssignBlanksPanelLayout = new javax.swing.GroupLayout(AssignBlanksPanel);
        AssignBlanksPanel.setLayout(AssignBlanksPanelLayout);
        AssignBlanksPanelLayout.setHorizontalGroup(
            AssignBlanksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AssignBlanksPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AssignBlanksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AssignBlanksPanelLayout.createSequentialGroup()
                        .addGroup(AssignBlanksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(AssignBlanksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lowerBlankNo1)
                            .addComponent(higherBlankNo1, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(AssignBlanksPanelLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(AssignBlanksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(AssignBlanksPanelLayout.createSequentialGroup()
                                .addGroup(AssignBlanksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(blankType1)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(AssignBlanksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(blankTypeCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(AssignBlanksPanelLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(advisorId, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(44, 44, 44))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AssignBlanksPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AssignBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170))
        );
        AssignBlanksPanelLayout.setVerticalGroup(
            AssignBlanksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AssignBlanksPanelLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(AssignBlanksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(advisorId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(AssignBlanksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(blankType1)
                    .addComponent(blankTypeCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AssignBlanksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lowerBlankNo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AssignBlanksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(higherBlankNo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(AssignBtn)
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout AssignBlanksLayout = new javax.swing.GroupLayout(AssignBlanks);
        AssignBlanks.setLayout(AssignBlanksLayout);
        AssignBlanksLayout.setHorizontalGroup(
            AssignBlanksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AssignBlanksLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(AssignBlanksPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AssignBlanksLayout.setVerticalGroup(
            AssignBlanksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AssignBlanksLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AssignBlanksPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        Commission.setBackground(new java.awt.Color(241, 223, 200));

        AddAmount.setText("Amount");

        AddCommBtn.setText("Add Commission");
        AddCommBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCommBtnActionPerformed(evt);
            }
        });

        ChangeCommBtn.setText("Change Commission");
        ChangeCommBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeCommBtnActionPerformed(evt);
            }
        });

        CurrentAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CurrentAmountActionPerformed(evt);
            }
        });

        jLabel2.setText("Current Commision Rate:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Domestic", "Interline" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel11.setText("Select Type:");

        javax.swing.GroupLayout CommissionLayout = new javax.swing.GroupLayout(Commission);
        Commission.setLayout(CommissionLayout);
        CommissionLayout.setHorizontalGroup(
            CommissionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CommissionLayout.createSequentialGroup()
                .addGroup(CommissionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CommissionLayout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(AddAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CommissionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(CommissionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel11))
                        .addGap(27, 27, 27)))
                .addGroup(CommissionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ChangeCommBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddCommBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CurrentAmount, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(208, Short.MAX_VALUE))
        );
        CommissionLayout.setVerticalGroup(
            CommissionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CommissionLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(CommissionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(47, 47, 47)
                .addGroup(CommissionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CurrentAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(CommissionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CommissionLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(AddCommBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ChangeCommBtn))
                    .addGroup(CommissionLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(AddAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ManagerDynamicPanelLayout = new javax.swing.GroupLayout(ManagerDynamicPanel);
        ManagerDynamicPanel.setLayout(ManagerDynamicPanelLayout);
        ManagerDynamicPanelLayout.setHorizontalGroup(
            ManagerDynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ManagerDynamicPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(ManagerDynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ManagerDynamicPanelLayout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(Advisor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(ManagerDynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ManagerDynamicPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Currency, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(ManagerDynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ManagerDynamicPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(AssignBlanks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(ManagerDynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ManagerDynamicPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Commission, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        ManagerDynamicPanelLayout.setVerticalGroup(
            ManagerDynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManagerDynamicPanelLayout.createSequentialGroup()
                .addComponent(Dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 489, Short.MAX_VALUE))
            .addGroup(ManagerDynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ManagerDynamicPanelLayout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(Advisor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(ManagerDynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ManagerDynamicPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Currency, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(ManagerDynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ManagerDynamicPanelLayout.createSequentialGroup()
                    .addGap(272, 272, 272)
                    .addComponent(AssignBlanks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(272, 272, 272)))
            .addGroup(ManagerDynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ManagerDynamicPanelLayout.createSequentialGroup()
                    .addGap(367, 367, 367)
                    .addComponent(Commission, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(368, 368, 368)))
        );

        ManagerTopPanel.setBackground(new java.awt.Color(0, 0, 51));
        ManagerTopPanel.setPreferredSize(new java.awt.Dimension(801, 126));

        AirViaLtdLabel16.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        AirViaLtdLabel16.setForeground(new java.awt.Color(255, 153, 51));
        AirViaLtdLabel16.setText("AirViaLtd");

        PlaneImg16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ATS/images/plane.png"))); // NOI18N

        javax.swing.GroupLayout ManagerTopPanelLayout = new javax.swing.GroupLayout(ManagerTopPanel);
        ManagerTopPanel.setLayout(ManagerTopPanelLayout);
        ManagerTopPanelLayout.setHorizontalGroup(
            ManagerTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ManagerTopPanelLayout.createSequentialGroup()
                .addContainerGap(235, Short.MAX_VALUE)
                .addComponent(PlaneImg16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AirViaLtdLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(227, 227, 227))
        );
        ManagerTopPanelLayout.setVerticalGroup(
            ManagerTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManagerTopPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ManagerTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ManagerTopPanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(AirViaLtdLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PlaneImg16, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        ManagerMenuPanel.setBackground(new java.awt.Color(0, 0, 51));
        ManagerMenuPanel.setPreferredSize(new java.awt.Dimension(145, 213));

        Home.setText("Home");
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });

        ReportsButton.setText("Reports");
        ReportsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportsButtonActionPerformed(evt);
            }
        });

        BlanksButton.setText("Blanks");
        BlanksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlanksButtonActionPerformed(evt);
            }
        });

        CommissionButton.setText("Commission");
        CommissionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CommissionButtonActionPerformed(evt);
            }
        });

        LogOut.setText("Log Out");
        LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutActionPerformed(evt);
            }
        });

        AdvisorBtn.setText("Advisor");
        AdvisorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdvisorBtnActionPerformed(evt);
            }
        });

        CurrencyBtn.setText("Currency");
        CurrencyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CurrencyBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ManagerMenuPanelLayout = new javax.swing.GroupLayout(ManagerMenuPanel);
        ManagerMenuPanel.setLayout(ManagerMenuPanelLayout);
        ManagerMenuPanelLayout.setHorizontalGroup(
            ManagerMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManagerMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ManagerMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(LogOut, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(CommissionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(ReportsButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Home, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BlanksButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AdvisorBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CurrencyBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        ManagerMenuPanelLayout.setVerticalGroup(
            ManagerMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManagerMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Home)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ReportsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BlanksButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CommissionButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AdvisorBtn)
                .addGap(6, 6, 6)
                .addComponent(CurrencyBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LogOut)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ManagerMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ManagerDynamicPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ManagerTopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ManagerTopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ManagerMenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1041, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ManagerDynamicPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        setSize(new java.awt.Dimension(819, 558));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        Dashboard.setVisible(true);
        AssignBlanks.setVisible(false);
        Commission.setVisible(false);
        Advisor.setVisible(false);
        Currency.setVisible(false);
    }//GEN-LAST:event_HomeActionPerformed

    private void ReportsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportsButtonActionPerformed
        Dashboard.setVisible(false);
        AssignBlanks.setVisible(false);
        Commission.setVisible(false);
        Advisor.setVisible(false);
        Currency.setVisible(false);
        new ViewTurnover().setVisible(true);
    }//GEN-LAST:event_ReportsButtonActionPerformed

    private void BlanksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlanksButtonActionPerformed
        Dashboard.setVisible(false);
        AssignBlanks.setVisible(true);
        Commission.setVisible(false);
        Advisor.setVisible(false);
        Currency.setVisible(false);
    }//GEN-LAST:event_BlanksButtonActionPerformed

    private void CommissionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CommissionButtonActionPerformed
        Dashboard.setVisible(false);
        AssignBlanks.setVisible(false);
        Commission.setVisible(true);
        Advisor.setVisible(false);
        Currency.setVisible(false);
    }//GEN-LAST:event_CommissionButtonActionPerformed

    private void LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutActionPerformed
        // TODO add your handling code here:
        //Log out and go back to login page
        new Login().setVisible(true); //Make Login form visible
        this.dispose(); //Dispose of this form (Admin)
    }//GEN-LAST:event_LogOutActionPerformed

    private void ChangeCommBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeCommBtnActionPerformed
        // TODO add your handling code here:
        conn = Driver.ConnectDB();
        int comm = Integer.parseInt(AddAmount.getText());
        
        String Sql = "UPDATE commissionrate set rate = '" + AddAmount.getText() + "', type = '" + jComboBox1.getSelectedItem() + "', trsvelagent_travelagentid = '1'";
         try {
            if (!(AddAmount.getText().trim().isEmpty())) {
                pst = conn.prepareStatement(Sql);
                pst.executeUpdate(Sql);

                JOptionPane.showMessageDialog(null, "Amount Successfully Changed.");

            } else {
                JOptionPane.showMessageDialog(null, "Please Input Amount.");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_ChangeCommBtnActionPerformed

    private void AddCommBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCommBtnActionPerformed
        // TODO add your handling code here:
        conn = Driver.ConnectDB();
        int comm = Integer.parseInt(AddAmount.getText());
        
        String Sql = "UPDATE commissionrate set rate = '" + AddAmount.getText() + "', type = '" + jComboBox1.getSelectedItem() + "', trsvelagent_travelagentid = '1'";
         try {
            if (!(AddAmount.getText().trim().isEmpty())) {
                pst = conn.prepareStatement(Sql);
                pst.executeUpdate(Sql);

                JOptionPane.showMessageDialog(null, "Amount Added Successfully.");

            } else {
                JOptionPane.showMessageDialog(null, "Please Input Amount.");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_AddCommBtnActionPerformed

    private void CurrentAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CurrentAmountActionPerformed
        // TODO add your handling code here
        conn = Driver.ConnectDB();
        try {
            Statement stmt = conn.createStatement();
            ResultSet rs;
 
            rs = stmt.executeQuery("SELECT Commission FROM Commission Rate");
            while ( rs.next() ) {
                String Rate = rs.getString("Rate");
                System.out.println(Rate);
            }
            conn.close();
        } catch (Exception e) {
            System.err.println("Got an exception! ");
            System.err.println(e.getMessage());
        }
        
    }//GEN-LAST:event_CurrentAmountActionPerformed

    private void lowerBlankNo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lowerBlankNo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lowerBlankNo1ActionPerformed

    private void AssignBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssignBtnActionPerformed
        // TODO add your handling code here:
        conn = Driver.ConnectDB();
        String advisor = advisorId.getText();
        String blankIdLower = blankTypeCombo1.getSelectedItem().toString() + lowerBlankNo1.getText();
        String blankIdHigher = blankTypeCombo1.getSelectedItem().toString() + higherBlankNo1.getText();

        long lowerBlank = Long.parseLong(blankIdLower);
        long higherBlank = Long.parseLong(blankIdHigher);

        
        //If all fields are field in the show register sucessful message
        try {

            if (!(lowerBlankNo1.getText().trim().isEmpty()) && !(higherBlankNo1.getText().trim().isEmpty())) {
                while (lowerBlank <= higherBlank) {
                    String Sql1 = "UPDATE blanks SET user_userId = '" + advisorId.getText() + "' WHERE blankId = '" + lowerBlank + "'";
                    pst = conn.prepareStatement(Sql1);
                    pst.executeUpdate(Sql1);
                    lowerBlank++;
                }
                conn.close();
                JOptionPane.showMessageDialog(null, "Blanks have been assigned.");

            } else {
                JOptionPane.showMessageDialog(null, "Fill in all fields.");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_AssignBtnActionPerformed

    private void advisorIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_advisorIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_advisorIdActionPerformed

    private void AdvisorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdvisorBtnActionPerformed
        // TODO add your handling code here:
        Dashboard.setVisible(false);
        AssignBlanks.setVisible(false);
        Commission.setVisible(false);
        Advisor.setVisible(true);
        Currency.setVisible(false);
        
    }//GEN-LAST:event_AdvisorBtnActionPerformed

    private void CurrencyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CurrencyBtnActionPerformed
        // TODO add your handling code here:
        Dashboard.setVisible(false);
        AssignBlanks.setVisible(false);
        Commission.setVisible(false);
        Advisor.setVisible(false);
        Currency.setVisible(true);
    }//GEN-LAST:event_CurrencyBtnActionPerformed

    private void FindUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindUserActionPerformed
        // TODO add your handling code here:
        String advisorID = InputID.getText();
        conn = Driver.ConnectDB();
        
        try(Statement statement = conn.createStatement())
        {
            
            if (!advisorID.trim().isEmpty()) {

                String query = "select Name from TravelAgent where TravelAgentID =" + advisorID;
                String query2 = "select Address from TravelAgent where TravelAgentID =" + advisorID;
                
                ResultSet result = statement.executeQuery(query);
                String name = result.getString(query);
                ResultSet result2 = statement.executeQuery(query2);
                String address = result2.getString(query2);
                
                AdvisorName.setText(name);
                AdvisorAddress.setText(address);
            }
            
            else {
                JOptionPane.showMessageDialog(null, "Input User ID.");
            }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_FindUserActionPerformed

    private void CurrencyNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CurrencyNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CurrencyNameActionPerformed

    private void getRateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getRateBtnActionPerformed
        // TODO add your handling code here:
        String currency= CurrencyName.getText();
        
         
        try(Statement statement = conn.createStatement())
        {
            if (!(currency.trim().isEmpty())) {
                String rate = "select CurrentRate from ExchangeRate Where CurrencyName =" + currency;
                
                ResultSet result = statement.executeQuery(rate);
                String exchange = result.getString(rate);
                CurrencyRate.setText(exchange);
                
                
            }
            
            else {
                JOptionPane.showMessageDialog(null, "Input Currency Name.");
            }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_getRateBtnActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
           
            
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void setRateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setRateBtnActionPerformed
        
        String currency= CurrencyName.getText();
        
        String currencyname = "SELECT CurrencyName FROM exchangerate WHERE CurrencyName = '" + currency + "'";
        
        try
        {
            pst = conn.prepareStatement(currencyname);
            ResultSet rs = pst.executeQuery(currencyname);
            if (!(rs.next())) {
                String addname = "INSERT INTO exchangerate (CurrencyName, CurrentRate) values ('" + currency + "', '0')";
                pst = conn.prepareStatement(addname);
                pst.executeUpdate();
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        String rate = "UPDATE exchangerate set CurrentRate = '" + CurrencyRate.getText() + "' Where CurrencyName = '" + currency + "'";
        try
        {
            if (!(currency.trim().isEmpty())) {
                pst = conn.prepareStatement(rate);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Currency Updated");
                
            }
            
            else {
                JOptionPane.showMessageDialog(null, "Input Currency Name.");
            }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_setRateBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddAmount;
    private javax.swing.JButton AddCommBtn;
    private javax.swing.JPanel Advisor;
    private javax.swing.JTextArea AdvisorAddress;
    private javax.swing.JButton AdvisorBtn;
    private javax.swing.JTextField AdvisorName;
    private javax.swing.JLabel AirViaLtdLabel16;
    private javax.swing.JPanel AssignBlanks;
    private javax.swing.JPanel AssignBlanksPanel;
    private javax.swing.JButton AssignBtn;
    private javax.swing.JButton BlanksButton;
    private javax.swing.JButton ChangeCommBtn;
    private javax.swing.JPanel Commission;
    private javax.swing.JButton CommissionButton;
    private javax.swing.JPanel Currency;
    private javax.swing.JButton CurrencyBtn;
    private javax.swing.JTextField CurrencyName;
    private javax.swing.JTextField CurrencyRate;
    private javax.swing.JTextField CurrentAmount;
    private javax.swing.JPanel Dashboard;
    private javax.swing.JButton FindUser;
    private javax.swing.JButton Home;
    private javax.swing.JTextField InputID;
    private javax.swing.JButton LogOut;
    private javax.swing.JPanel ManagerDynamicPanel;
    private javax.swing.JPanel ManagerMenuPanel;
    private javax.swing.JPanel ManagerTopPanel;
    private javax.swing.JLabel PlaneImg16;
    private javax.swing.JButton ReportsButton;
    private javax.swing.JTextField advisorId;
    private javax.swing.JLabel blankType1;
    private javax.swing.JComboBox<String> blankTypeCombo1;
    private javax.swing.JButton getRateBtn;
    private javax.swing.JTextField higherBlankNo1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField lowerBlankNo1;
    private javax.swing.JButton setRateBtn;
    // End of variables declaration//GEN-END:variables
}
